import 'dart:io';

import 'package:file_picker/file_picker.dart';
import 'package:path_provider/path_provider.dart';
// ignore: depend_on_referenced_packages
import 'package:path/path.dart';
import 'package:share_plus/share_plus.dart';
import 'package:sqflite/sqflite.dart';

import 'package:my_people/helpers/database_helper.dart';
import 'package:my_people/model/person.dart';

class BackupHelper {
  static const String _backupExtension = '.myppl';
  static const String _databaseName =
      "myDatabase.db"; // Matching DatabaseHelper

  static Future<bool> createBackup() async {
    try {
      final dbPath = await _getDatabasePath();
      final File dbFile = File(dbPath);
      if (!await dbFile.exists()) {
        return false;
      }
      final tempDir = await getTemporaryDirectory();
      final backupFileName =
          'mypeople_backup${DateTime.now().millisecondsSinceEpoch}$_backupExtension';
      final tempBackupFile = File('${tempDir.path}/$backupFileName');

      await dbFile.copy(tempBackupFile.path);

      final result = await SharePlus.instance.share(ShareParams(
        files: [XFile(tempBackupFile.path)],
        subject: 'MyPeople Backup',
      ));

      return result.status == ShareResultStatus.success;
    } catch (e) {
      return false;
    }
  }

  static Future<bool> importBackup() async {
    try {
      FilePickerResult? result = await FilePicker.platform.pickFiles(
        type: FileType.custom,
        allowedExtensions: ['myppl'],
      );

      if (result == null || result.files.single.path == null) return false;
      String backupPath = result.files.single.path!;

      final File backupFile = File(backupPath);
      if (!await backupFile.exists()) return false;

      // Validate the imported file by opening it
      final backupDb = await openDatabase(backupFile.path);

      try {
        final check = await backupDb.rawQuery('PRAGMA integrity_check');
        if (check.first.values.first != 'ok') {
          throw Exception('Integrity check failed');
        }

        // Fetch all persons from the backup
        final List<Map<String, dynamic>> maps = await backupDb.query('persons');

        // Add them to the current database
        for (var map in maps) {
          // Remove UUID so a new one is generated by Person.fromMap/constructor
          Map<String, dynamic> mutableMap = Map<String, dynamic>.from(map);
          mutableMap.remove('uuid');

          final person = Person.fromMap(mutableMap);
          await DatabaseHelper.instance.insertPerson(person);
        }

        await backupDb.close();
        return true;
      } catch (e) {
        await backupDb.close();
        return false;
      }
    } catch (e) {
      return false;
    }
  }

  static Future<String> _getDatabasePath() async {
    Directory documentsDirectory = await getApplicationDocumentsDirectory();
    return join(documentsDirectory.path, _databaseName);
  }
}
