name: my_people
publish_to: none
version: 4.1.0+7
description: An app for noting details about people.

dev_dependencies:
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter

environment:
  sdk: ">=3.2.6 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  connectivity_plus: ^7.0.0
  cupertino_icons: ^1.0.2
  dio: ^5.4.3+1
  firebase_analytics: ^12.1.2
  firebase_core: ^4.4.0
  flutter_dotenv: ^6.0.0
  flutter_markdown: ^0.7.6+2
  flutter_svg: ^2.0.10+1
  get: ^4.6.6
  google_generative_ai: ^0.4.3
  icons_launcher: ^3.0.1
  image_picker: ^1.0.8
  install_plugin: ^2.1.0
  package_info_plus: ^9.0.0
  path_provider: ^2.0.2
  shared_preferences: ^2.2.3
  sqflite: ^2.0.0
  uuid: ^4.4.0

flutter:
  assets:
    - assets/
    - assets/arrows/
    - assets/profile_pictures/
    - .env
  uses-material-design: true
