dependencies:
  connectivity_plus: ^6.0.3
  cupertino_icons: ^1.0.2
  dio: ^5.4.3+1
  firebase_analytics: ^11.4.4
  firebase_core: ^3.12.1
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.1.0
  flutter_markdown: ^0.7.6+2
  flutter_svg: ^2.0.10+1
  get: ^4.6.6
  google_generative_ai: ^0.4.3
  icons_launcher: ^3.0.1
  image_picker: ^1.0.8
  install_plugin: ^2.1.0
  package_info_plus: ^8.3.0
  path_provider: ^2.0.2
  shared_preferences: ^2.2.3
  sqflite: ^2.0.0
  uuid: ^4.4.0
description: An app for noting details about people.
dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
environment:
  sdk: ">=3.2.6 <4.0.0"
flutter:
  assets:
    - assets/
    - .env
  uses-material-design: true
name: my_people
publish_to: none
version: 4.0.0+1
