dependencies:
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  get: ^4.6.6
  icons_launcher: ^2.1.7
  image_picker: ^1.0.8
  path_provider: ^2.0.2
  sqflite: ^2.0.0
  uuid: ^4.4.0
description: An app for noting details about people.
dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
environment:
  sdk: '>=3.2.6 <4.0.0'
flutter:
  assets:
  - assets/
  uses-material-design: true
name: my_people
publish_to: none
version: 1.0.0
